services:
  db:
    image: postgres:16
    container_name: eluryn-db
    environment:
      POSTGRES_USER: eluryn
      POSTGRES_PASSWORD: eluryn
      POSTGRES_DB: eluryn
    ports:
      - "5433:5432"
    volumes:
      - eluryn_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eluryn -d eluryn"]
      interval: 5s
      timeout: 3s
      retries: 20

  flyway:
    image: flyway/flyway:10
    container_name: eluryn-flyway
    depends_on:
      db:
        condition: service_healthy
    command: >
      -url=jdbc:postgresql://db:5432/eluryn
      -user=eluryn
      -password=eluryn
      -connectRetries=30
      -schemas=users,pomotimer
      migrate
    volumes:
      - ./backend/Eluryn.Api/db/migrations:/flyway/sql:ro

  # api:
  #   build:
  #     context: .
  #     dockerfile: backend/Eluryn.Api/Dockerfile
  #   container_name: eluryn-api
  #   depends_on:
  #     flyway:
  #       condition: service_completed_successfully
  #   environment:
  #     ASPNETCORE_URLS: http://+:8080
  #     ConnectionStrings__Default: Host=db;Port=5432;Database=eluryn;Username=eluryn;Password=eluryn
  #   ports:
  #     - "8080:8080"

volumes:
  eluryn_pgdata:
