services:
  traefik:
    image: traefik:v3
    networks:
      edge:
        ipv4_address: 172.20.0.10 # static IP for traefik in edge network so backend services can add it to known proxies
    security_opt:
      - no-new-privileges:true
    command:
      # when routing to containers, use the edge network IPs
      - --providers.docker.network=eluryn-edge
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - "--entrypoints.websecure.http.tls=true"
      - --providers.file.directory=/etc/traefik/dynamic
      - --providers.file.watch=true
      # redirect all http to https
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      # make sure the redirect sceheme is https
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      # Enables Traefik access logs (every request through Traefik gets logged)
      - --accesslog=true

    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # Traefik dashboard (local only)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/dynamic:/etc/traefik/dynamic:ro
      - ../../certs:/certs:ro
  db:
    image: postgres:16
    networks:
      - internal
    environment:
      POSTGRES_DB: eluryn
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "15432:5432"
    volumes:
      - eluryn-db:/var/lib/postgresql/data
      - ./local.db.init.sql:/docker-entrypoint-initdb.d/00-init.sql:ro

  flyway-users:
    image: flyway/flyway:11.20.1
    networks:
      - internal
    depends_on:
      - db
    command:
      [
        "-url=jdbc:postgresql://db:5432/eluryn",
        "-user=users_svc",
        "-password=users_pw",
        "-connectRetries=30",
        "-schemas=users",
        "migrate"
      ]
    volumes:
      - ../../backend/services/Users/Eluryn.Users.Api/migrations:/flyway/sql:ro

  flyway-pomotimer:
    image: flyway/flyway:11.20.1
    networks:
      - internal
    depends_on:
      - db
    command:
      [
        "-url=jdbc:postgresql://db:5432/eluryn",
        "-user=pomotimer_svc",
        "-password=pomo_pw",
        "-connectRetries=30",
        "-schemas=pomotimer",
        "migrate"
      ]
    volumes:
      - ../../backend/services/Pomotimer/Eluryn.Pomotimer.Api/migrations:/flyway/sql:ro

  users-api:
    build:
      context: ../../backend/services/Users/Eluryn.Users.Api
    depends_on:
      - flyway-users
    networks:
      - edge
      - internal
    environment:
      ConnectionStrings__Db: Host=db;Port=5432;Database=eluryn;Username=users_svc;Password=users_pw
      ASPNETCORE_ENVIRONMENT: Development
      Logging__LogLevel__Default: Information
      Logging__LogLevel__Microsoft.AspNetCore: Warning
    labels:
      - traefik.enable=true
      # creates a router named "users" that listens to api.localhost/users
      - traefik.http.routers.users.rule=Host(`api.localhost`) && PathPrefix(`/users`)
      # removes the /users prefix when forwarding to the service. So a request to api.localhost/users/weatherforecast becomes /weatherforecast to the service.
      # So it will be forwarded to http://<users-api-container-ip>:8080/weatherforecast.
      - traefik.http.middlewares.users-stripprefix.stripprefix.prefixes=/users
      - traefik.http.services.users.loadbalancer.server.port=8080

      # CORS middleware (local)
      - traefik.http.middlewares.users-cors.headers.accesscontrolalloworiginlist=https://localhost:5173,http://localhost:5173
      - traefik.http.middlewares.users-cors.headers.accesscontrolallowmethods=GET,OPTIONS,PUT,POST,DELETE,PATCH
      - traefik.http.middlewares.users-cors.headers.accesscontrolallowheaders=*
      - traefik.http.middlewares.users-cors.headers.addvaryheader=true

      # Attaches both middlewares to the router, in that order
      - traefik.http.routers.users.middlewares=users-stripprefix,users-cors

      # This router listens on HTTPS only (port 443 entrypoint) 
      - traefik.http.routers.users.entrypoints=websecure
      # Enables TLS termination for this router
      - traefik.http.routers.users.tls=true

  pomotimer-api:
    build:
      context: ../../backend/services/Pomotimer/Eluryn.Pomotimer.Api
    depends_on:
      - flyway-pomotimer
    networks:
      - edge
      - internal
    environment:
      ConnectionStrings__Db: Host=db;Port=5432;Database=eluryn;Username=pomotimer_svc;Password=pomo_pw
      ASPNETCORE_ENVIRONMENT: Development
      Logging__LogLevel__Default: Information
      Logging__LogLevel__Microsoft.AspNetCore: Warning
    labels:
      - traefik.enable=true
      - traefik.http.routers.pomotimer.rule=Host(`api.localhost`) && PathPrefix(`/pomotimer`)
      - traefik.http.middlewares.pomotimer-stripprefix.stripprefix.prefixes=/pomotimer

      - traefik.http.middlewares.pomotimer-cors.headers.accesscontrolalloworiginlist=https://localhost:5173,http://localhost:5173
      - traefik.http.middlewares.pomotimer-cors.headers.accesscontrolallowmethods=GET,OPTIONS,PUT,POST,DELETE,PATCH
      - traefik.http.middlewares.pomotimer-cors.headers.accesscontrolallowheaders=*
      - traefik.http.middlewares.pomotimer-cors.headers.addvaryheader=true

      - traefik.http.routers.pomotimer.middlewares=pomotimer-stripprefix,pomotimer-cors

      - traefik.http.routers.pomotimer.entrypoints=websecure
      - traefik.http.routers.pomotimer.tls=true

      - traefik.http.services.pomotimer.loadbalancer.server.port=8080

  # frontend:
  #   build:
  #     context: ../frontend
  #     dockerfile: Dockerfile.local
  #   depends_on:
  #     - users-api
  #     - pomotimer-api
  #   ports:
  #     - "5173:5173"
  #   labels:
  #     - traefik.enable=true
  #     - traefik.http.routers.frontend.rule=Host(`app.localhost`)
  #     - traefik.http.routers.frontend.entrypoints=web
  #     - traefik.http.services.frontend.loadbalancer.server.port=5173
  #   develop:
  #     watch:
  #       - path: ../frontend/src
  #         target: /app/src
  #         action: sync
  #       - path: ../frontend/package.json
  #         target: /app/package.json
  #         action: restart
  #       - path: ../frontend/vite.config.ts
  #         target: /app/vite.config.ts
  #         action: restart

volumes:
  eluryn-db:

networks:
  edge:
    name: eluryn-edge
    ipam:
      config:
        - subnet: 172.20.0.0/16
  internal:
    name: eluryn-internal
    internal: true
    ipam:
      config:
        - subnet: 172.21.0.0/16
