services:
  traefik:
    image: traefik:v3
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.file.directory=/etc/traefik/dynamic
      - --providers.file.watch=true
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --accesslog=true

    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # Traefik dashboard (local only)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/dynamic:/etc/traefik/dynamic:ro
      - ../certs:/certs:ro
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: eluryn
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "15432:5432"
    volumes:
      - eluryn-db:/var/lib/postgresql/data
      - ./local.db.init.sql:/docker-entrypoint-initdb.d/00-init.sql:ro

#! how come flyway dont need to use labels for traefik like the apis?
  flyway-users:
    image: flyway/flyway:11.20.1
    depends_on:
      - db
    command:
      [
        "-url=jdbc:postgresql://db:5432/eluryn",
        "-user=users_svc",
        "-password=users_pw",
        "-connectRetries=30",
        "-schemas=users",
        "migrate"
      ]
    volumes:
      - ../backend/services/Users/Eluryn.Users.Api/migrations:/flyway/sql:ro

  flyway-pomotimer:
    image: flyway/flyway:11.20.1
    depends_on:
      - db
    command:
      [
        "-url=jdbc:postgresql://db:5432/eluryn",
        "-user=pomotimer_svc",
        "-password=pomo_pw",
        "-connectRetries=30",
        "-schemas=pomotimer",
        "migrate"
      ]
    volumes:
      - ../backend/services/Pomotimer/Eluryn.Pomotimer.Api/migrations:/flyway/sql:ro

  users-api:
    build:
      context: ../backend/services/Users/Eluryn.Users.Api
    depends_on:
      - flyway-users
    environment:
      ConnectionStrings__Db: Host=db;Port=5432;Database=eluryn;Username=users_svc;Password=users_pw
    labels:
      - traefik.enable=true
      - traefik.http.routers.users.rule=Host(`api.localhost`) && PathPrefix(`/users`)
      # - traefik.http.routers.users.entrypoints=web
      - traefik.http.middlewares.users-stripprefix.stripprefix.prefixes=/users
      # - traefik.http.routers.users.middlewares=users-stripprefix

      # ✅ CORS middleware (local)
      - traefik.http.middlewares.users-cors.headers.accesscontrolalloworiginlist=https://localhost:5173,http://localhost:5173
      - traefik.http.middlewares.users-cors.headers.accesscontrolallowmethods=GET,OPTIONS,PUT,POST,DELETE,PATCH
      - traefik.http.middlewares.users-cors.headers.accesscontrolallowheaders=*
      - traefik.http.middlewares.users-cors.headers.addvaryheader=true

      # apply both middlewares
      - traefik.http.routers.users.middlewares=users-stripprefix,users-cors

      - traefik.http.routers.users.entrypoints=websecure
      - traefik.http.routers.users.tls=true

      - traefik.http.services.users.loadbalancer.server.port=8080

  pomotimer-api:
    build:
      context: ../backend/services/Pomotimer/Eluryn.Pomotimer.Api
    depends_on:
      - flyway-pomotimer
    environment:
      ConnectionStrings__Db: Host=db;Port=5432;Database=eluryn;Username=pomotimer_svc;Password=pomo_pw
    labels:
      - traefik.enable=true
      - traefik.http.routers.pomotimer.rule=Host(`api.localhost`) && PathPrefix(`/pomotimer`)
      # - traefik.http.routers.pomotimer.entrypoints=web
      - traefik.http.middlewares.pomotimer-stripprefix.stripprefix.prefixes=/pomotimer
      # - traefik.http.routers.pomotimer.middlewares=pomotimer-stripprefix

      # ✅ CORS middleware (local)
      - traefik.http.middlewares.pomotimer-cors.headers.accesscontrolalloworiginlist=https://localhost:5173,http://localhost:5173
      - traefik.http.middlewares.pomotimer-cors.headers.accesscontrolallowmethods=GET,OPTIONS,PUT,POST,DELETE,PATCH
      - traefik.http.middlewares.pomotimer-cors.headers.accesscontrolallowheaders=*
      - traefik.http.middlewares.pomotimer-cors.headers.addvaryheader=true

      # apply both middlewares
      - traefik.http.routers.pomotimer.middlewares=pomotimer-stripprefix,pomotimer-cors

      - traefik.http.routers.pomotimer.entrypoints=websecure
      - traefik.http.routers.pomotimer.tls=true

      - traefik.http.services.pomotimer.loadbalancer.server.port=8080

  # frontend:
  #   build:
  #     context: ../frontend
  #     dockerfile: Dockerfile.local
  #   depends_on:
  #     - users-api
  #     - pomotimer-api
  #   ports:
  #     - "5173:5173"
  #   labels:
  #     - traefik.enable=true
  #     - traefik.http.routers.frontend.rule=Host(`app.localhost`)
  #     - traefik.http.routers.frontend.entrypoints=web
  #     - traefik.http.services.frontend.loadbalancer.server.port=5173
  #   develop:
  #     watch:
  #       - path: ../frontend/src
  #         target: /app/src
  #         action: sync
  #       - path: ../frontend/package.json
  #         target: /app/package.json
  #         action: restart
  #       - path: ../frontend/vite.config.ts
  #         target: /app/vite.config.ts
  #         action: restart

volumes:
  eluryn-db:
